// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/ble/v1/ble.proto

package ble

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14f5b201651cf47, []int{0}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type DataResponse struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14f5b201651cf47, []int{1}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DataResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DataResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "ble.StreamRequest")
	proto.RegisterType((*DataResponse)(nil), "ble.DataResponse")
}

func init() {
	proto.RegisterFile("api/ble/v1/ble.proto", fileDescriptor_b14f5b201651cf47)
}

var fileDescriptor_b14f5b201651cf47 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0x15, 0xb5, 0xe3, 0x7a, 0x70, 0xf0, 0x50, 0xd4, 0x43, 0x59, 0x10, 0x7b, 0x90,
	0xd6, 0x0f, 0xfc, 0x03, 0xb2, 0x17, 0xaf, 0xd9, 0xdb, 0x5e, 0x24, 0x6d, 0x87, 0x35, 0x90, 0x26,
	0x31, 0x99, 0x2e, 0xec, 0xbf, 0x97, 0x74, 0x2d, 0xea, 0xe9, 0x9d, 0x79, 0x18, 0x86, 0x87, 0x17,
	0xae, 0x94, 0xd7, 0x4d, 0x6b, 0xa8, 0xd9, 0x3d, 0xa5, 0xa8, 0x7d, 0x70, 0xec, 0x30, 0x6b, 0x0d,
	0x2d, 0x1f, 0xe0, 0x62, 0xcd, 0x81, 0xd4, 0x20, 0xe9, 0x6b, 0xa4, 0xc8, 0x78, 0x03, 0x79, 0x67,
	0x34, 0x59, 0xfe, 0xd0, 0x7d, 0x21, 0x4a, 0x51, 0xe5, 0xf2, 0xec, 0x00, 0xde, 0xfb, 0xe5, 0x06,
	0x16, 0x2b, 0xc5, 0x4a, 0x52, 0xf4, 0xce, 0x46, 0x42, 0x84, 0x63, 0xde, 0x7b, 0xfa, 0xb9, 0x9b,
	0x66, 0x2c, 0xe0, 0xd4, 0xab, 0xbd, 0x71, 0xaa, 0x2f, 0x8e, 0x4a, 0x51, 0x2d, 0xe4, 0xbc, 0xe2,
	0x2d, 0xe4, 0xac, 0x07, 0x8a, 0xac, 0x06, 0x5f, 0x64, 0xa5, 0xa8, 0x32, 0xf9, 0x0b, 0x9e, 0x57,
	0x70, 0x9e, 0x7e, 0xaf, 0x29, 0xec, 0x74, 0x47, 0xf8, 0x0a, 0x70, 0x10, 0x4b, 0x10, 0xb1, 0x4e,
	0xde, 0xff, 0x4c, 0xaf, 0x2f, 0x27, 0xf6, 0xd7, 0xe7, 0x51, 0xbc, 0xdd, 0x6f, 0xee, 0xb6, 0x9a,
	0x3f, 0xc7, 0xb6, 0xee, 0xdc, 0xd0, 0x84, 0xd1, 0xd0, 0xd6, 0xcd, 0x41, 0xb6, 0xf7, 0x4e, 0x5b,
	0x4e, 0x1d, 0xb4, 0x27, 0x53, 0x09, 0x2f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x61, 0x68,
	0xaf, 0x1c, 0x01, 0x00, 0x00,
}
